### ISSUE TITLE
No settings or keybind file when installing via package manager

### ISSUE THREAD

**Issue by Phunky** [evanliomain/sublime-ExpandGroup#1]
Just installed the plugin and love it great job!

Wanted to slightly tweak the ratio but seems the config files don't exist on OSX?

**Comment by evanliomain** [comment]
Issue should be solved in the 1.0.1 release.
If it's not, try to import the plugin manualy by cloning this repo in your "Packages" directory.

Be carefull of the <kbd>alt+up</kbd> and <kbd>alt+down</kbd> shortcut which can be overriden by another plugin, such as "Emmet".
