### ISSUE TITLE
ST3 Crashes

### ISSUE THREAD

**Issue by jomurgel** [evanliomain/sublime-ExpandGroup#2]
ST3 Crashes when attempting to remove a column.  Going from 3 to 2 for instance.  Works fine without ExpandGroup.  Works fine with ExpandGroup adding columns.

**Comment by evanliomain** [comment]
I don't figure out what you intented to do.
Did you mean you try to switch between a 3 columns layout (View > Layout > Columns:3) to a 2 columns layout (View > Layout > Columns:2). In that case : 
- ExpandGroup is not working for a 3 columns layout
- I don't crash ST3 on that move.
